spring:
  data:
    mongodb:
      database: check_code
      uri: mongodb://${MONGO_HOST:localhost:27017}/check_code?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000

  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    consumer:
      group-id: ${GROUP_ID:report}